### ISSUE TITLE
Switchboard-Sharing complains about missing sharing link

### ISSUE THREAD

**Issue by hashmich** [clarin-eric/B2Drop2LRSwitchboard#1]
The xhr request seemingly does not receive any sharing link, nor any data at all: 
![b2drop-lrs-bridge-malfunction](https://user-images.githubusercontent.com/178177/38647263-a8a4e37a-3deb-11e8-9903-cb39f9a8717c.png)

**Comment by claus-zinn** [comment]
Are you sure you ticked the box, see attachment. I recently changed the pop-up message because users wanted to share the file with friends (and hence used the textinput box).

<img width="308" alt="share" src="https://user-images.githubusercontent.com/16115677/38660635-3c918fb0-3e2e-11e8-86b6-96ba9bbbddcb.png">

Is this your local installation? Which NC version?

**Comment by hashmich** [comment]
Issue fixed by commit a416dae380531e17f6c868cba5e92e85f56b2192 on May, 3rd 2018
The xhr request missed the full file path in the parameter to successfully identify the file. Was only working in root folder, where just the file name was sufficient.
