### ISSUE TITLE
Nextcloud15 support

### ISSUE THREAD

**Issue by apw1388** [clarin-eric/B2Drop2LRSwitchboard#4]
Please update the app to support Nextcloud 15.

**Comment by hashmich** [comment]
Does a timeline already exist, until when a first analysis should be done?

**Comment by apw1388** [comment]
We do not have a date for update, but we start to evaluate the latest version 15 release this week.

**Comment by claus-zinn** [comment]
If all goes well, we only have to change appinfo/info.xml and set max-version to 15. Will need to test, of course.

**Comment by hashmich** [comment]
I keep my fingers crossed for Claus being right ;)
I have lots of conference travel and preparations ahead, so I expect being able to look into that in week 21 the earliest. Will have to make myself familiar again with the setup...

**Comment by apw1388** [comment]
We are done with our tests and going to plan the update. This will lead to the loss of the switchboard app.

**Comment by hashmich** [comment]
I created a new nextcloud instance v15 including a new database by updating the Docker setup Claus provided to me. (do you use Docker for deployment in Jülich?)
I failed updating the existing instance and database, maybe because of messing with the NC updater too much.

The b2drop app semed to work just fine after re-enabling it in the web interface.
However, the theme turned out to be broken and would need some fixes. 

Can you share some details on your deployment process?
